### ISSUE TITLE
Robotic Hand in the Paper

### ISSUE THREAD

**Issue by MingshanHe** [tengyu-liu/diverse-and-stable-grasp#1]
Hi! Thanks for your excellent work!
I want to know if you have opened the robotic hand version in this code.

**Comment by tengyu-liu** [comment]
Hi,

Thank you for your interest. We do not have plans to open source the
synthesis code for robotic hands. However, it should not be difficult to
adapt the code to doing so with a differentiable forward kinematic and a
method to sample possible contact points from the hand surface.

Best,
Tengyu

Dr. Tengyu Liu
Beijing Institute of General Artificial Intelligence (BIGAI)
+86 16600031170

**Comment by YuyangLee** [comment]
Hi,

The code for our latest work, [Grasp Multiple Objects with One Hand](https://multigrasp.github.io), contains the code for differentiable kinematics for robotic hands. You can find the code [here](https://github.com/MultiGrasp/MultiGrasp).

Best,
Yuyang Li
BIGAI | Institute for AI, PKU

**Comment by MingshanHe** [comment]
Thanks for your all kind replies and references.
